#systemctl enable SCAPE604-apri-sensor-service-arduinobin.service
systemctl enable SCAPE604-apri-sensor-service-bam1020.service
systemctl enable SCAPE604-apri-sensor-service-bme280.service
systemctl enable SCAPE604-apri-sensor-service-bme680.service
systemctl enable SCAPE604-apri-sensor-service-ds18b20.service
#systemctl enable SCAPE604-apri-sensor-service-dylos.service
systemctl enable SCAPE604-apri-sensor-service-ips7100.service
#systemctl enable SCAPE604-apri-sensor-service-knmi.service
systemctl enable SCAPE604-apri-sensor-service-nextpm.service
systemctl enable SCAPE604-apri-sensor-service-pms7003.service
systemctl enable SCAPE604-apri-sensor-service-pmsa003.service
systemctl enable SCAPE604-apri-sensor-service-pmsa003nm.service
systemctl enable SCAPE604-apri-sensor-service-radiationd.service
systemctl enable SCAPE604-apri-sensor-service-scd30.service
#systemctl enable SCAPE604-apri-sensor-service-sensorcontrol.service
#systemctl enable SCAPE604-apri-sensor-service-sensorselect.service
systemctl enable SCAPE604-apri-sensor-service-solar.service
systemctl enable SCAPE604-apri-sensor-service-sps30.service
#systemctl enable SCAPE604-apri-sensor-service-tgs5042.service
#systemctl enable SCAPE604-openiod.service